{% set version = '1.1' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-ensurer
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/ensurer_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/ensurer/ensurer_{{ version }}.tar.gz
  sha256: 2dce76bb869ef5bcde9b4d9f7197c41405d2bbf917a1d5e1afec7b354eb46bbd

build:
  merge_build_host: True  # [win]
  number: 1005
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
  run:
    - r-base

test:
  commands:
    - $R -e "library('ensurer')"           # [not win]
    - "\"%R%\" -e \"library('ensurer')\""  # [win]

about:
  home: https://github.com/smbache/ensurer
  license: MIT
  summary: Add simple runtime contracts to R values. These ensure that values fulfil certain
    conditions and will raise appropriate errors if they do not.
  license_family: MIT
  license_file:
    - '{{ environ["PREFIX"] }}/lib/R/share/licenses/MIT'
    - LICENSE

extra:
  recipe-maintainers:
    - conda-forge/r
    - MathiasHaudgaard
    - FrodePedersen
    - ArneKr

# Package: ensurer
# Type: Package
# Title: Ensure Values at Runtime
# Version: 1.1
# Author: Stefan Milton Bache
# Maintainer: Stefan Milton Bache <stefan@stefanbache.dk>
# Description: Add simple runtime contracts to R values. These ensure that values fulfil certain conditions and will raise appropriate errors if they do not.
# License: MIT + file LICENSE
# Suggests: magrittr, testthat, knitr
# VignetteBuilder: knitr
# ByteCompile: Yes
# URL: https://github.com/smbache/ensurer
# BugReports: https://github.com/smbache/ensurer/issues
# NeedsCompilation: no
# Packaged: 2015-04-21 19:08:43 UTC; shb
# Repository: CRAN
# Date/Publication: 2015-04-21 23:45:48
